from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TODOLIST.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^UserDetail/(.+)/$', 'userfunc.views.UserDetail'),
    url(r'^login/$', 'userfunc.views.login'),
    url(r'^register/$', 'userfunc.views.register'),
    url(r'^ForgetPwd/$', 'userfunc.views.ForgetPwd'),
    url(r'^TaskFinish/$', 'tasklist.views.TaskFinish'),
    url(r'^TaskFinishInCollect/$', 'tasklist.views.TaskFinishInCollect'),
    url(r'^TaskUnfinish/$', 'tasklist.views.TaskUnfinish'),
    url(r'^TodayTask/(.+)/$', 'tasklist.views.TodayTask'),
    url(r'^CollectedTask/(.+)/$', 'tasklist.views.CollectedTask'),
    url(r'^finished/(.+)/$', 'tasklist.views.FinishedTask'),
    url(r'^deleted/(.+)/$', 'tasklist.views.DeletedTask'),
    url(r'^TaskDelete/$', 'tasklist.views.TaskDelete'),
    url(r'^TaskDeleteInCollect/$', 'tasklist.views.TaskDeleteInCollect'),
    url(r'^TaskDeleteInFinish/$', 'tasklist.views.TaskDeleteInFinish'),
    url(r'^TaskDeleteInSitu/$', 'tasklist.views.TaskDeleteInSitu'),
    url(r'^TaskDeleteInMaybe/$', 'tasklist.views.TaskDeleteInMaybe'),
    url(r'^TaskFinishInMaybe/$', 'tasklist.views.TaskFinishInMaybe'),
    url(r'^TaskUndelet/$', 'tasklist.views.TaskUndelete'),
    url(r'^TaskDetail/id(.+)uid(.+)/$', 'tasklist.views.TaskDetail'),
    url(r'^DeletedTask/$', 'tasklist.views.DeletedTask'),
    url(r'^maybe/(.+)/$', 'tasklist.views.FutureTask'),
    url(r'^logout/(.+)/$', 'userfunc.views.logout'),
    url(r'^AddSituationpre/(.+)/$', 'tasklist.views.AddSituationpre'),
    url(r'^AddSituation/$', 'tasklist.views.AddSituation'),
    url(r'^SituationTask/uid(.+)sid(.+)/$', 'tasklist.views.SituationTask'),
    url(r'^AddTask/uid(.+)option(.+)/$', 'tasklist.views.AddTaskpre'),
    url(r'^searchtask/$', 'tasklist.views.searchtask'),
    url(r'^AddTask/$', 'tasklist.views.AddTask'),
    url(r'^ResetPwd/uid(.+)skey(.+)/$', 'userfunc.views.ResetPwdpre'),
    url(r'^ResetPwd/$', 'userfunc.views.ResetPwd'),
    url(r'^ChangeTaskpre/$', 'tasklist.views.ChangeTaskpre'),
    url(r'^ChangeTask/$', 'tasklist.views.ChangeTask'),
    url(r'^DeleteSituation/sid(.+)uid(.+)/$', 'tasklist.views.DeleteSituation'),
    url(r'^UserUpdatepre/(.+)/$', 'userfunc.views.UserUpdatepre'),
    url(r'^UserUpdate/$', 'userfunc.views.UserUpdate'),
    url(r'^admin/', include(admin.site.urls)),
)
